name: pdfarranger
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    container: jeromerobert/pdfarranger-docker-ci
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: pip3 install .
    - name: appstream
      run: appstreamcli validate /usr/local/share/metainfo/com.github.jeromerobert.pdfarranger.metainfo.xml
    - name: desktop-file-validate
      run: desktop-file-validate /usr/local/share/applications/com.github.jeromerobert.pdfarranger.desktop
